version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=${PORT}
      - ENVIRONMENT=${ENVIRONMENT}
      - SENTRY_DSN=${SENTRY_DSN}
    working_dir: /app
    volumes:
      - .:/app
    restart: unless-stopped