version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=${PORT}
      - ENVIRONMENT=${ENVIRONMENT}
      - SENTRY_DSN=${SENTRY_DSN}
    working_dir: /app
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/health >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s